use_frameworks!

platform :ios, '8.0'

target 'XJCollectionViewManager_Example' do
  pod 'XJCollectionViewManager', :path => '../'

  target 'XJCollectionViewManager_Tests' do
    inherit! :search_paths

    
  end
end
